spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sales_db}
    username: ${SPRING_DATASOURCE_USERNAME:sales}
    password: ${SPRING_DATASOURCE_PASSWORD:sales123}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
  thymeleaf:
    cache: ${SPRING_THYMELEAF_CACHE:false}

server:
  port: ${PORT:8080}

app:
  upload-dir: ${APP_UPLOAD_DIR:uploads}
